### ISSUE TITLE
Issue during run

### ISSUE THREAD

**Issue by Infernion** [gleb-sevruk/pycrunch-engine#1]
I've installed plugin and trying to run it but got next error. Maybe the problem with namespace packages that used in my lib but I'm not sure about it.

The traceback:
```
/Users/serhii/.pyenv/versions/eyes3/bin/python -m pycrunch.main --port=63350
/Users/serhii/.pyenv/versions/eyes3/lib/python3.7/site-packages/pycrunch
/Users/serhii/.pyenv/versions/eyes3/lib/python3.7/site-packages/pycrunch/log_configuration.yaml
PyCrunch port will be 63350
 * Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
2019-09-17 14:02:54,009 - pycrunch.api.socket_handlers - DEBUG - Client test_connected
2019-09-17 14:02:54,010 - pycrunch.runner.pipeline_dispatcher - DEBUG - Dispatcher thread -- Start
/Users/serhii/Projects/WORK/APPLITOOLS/eyes.sdk.python/.pycrunch-config.yaml
.pycrunch-config.yaml
{'discovery': {'exclusions': ['tests/functional/']}, 'engine': {'runtime': 'pytest'}}
<_io.TextIOWrapper name='.pycrunch-config.yaml' mode='r' encoding='utf-8'>
2019-09-17 14:02:54,017 - pycrunch.discovery.simple - DEBUG - ['/Users/serhii/Projects/WORK/APPLITOOLS/eyes.sdk.python', '/Users/serhii/Projects/WORK/APPLITOOLS/eyes.sdk.python', '/Users/serhii/Projects/WORK/APPLITOOLS/eyes.sdk.python/eyes_images', '/Users/serhii/Projects/WORK/APPLITOOLS/eyes.sdk.python/eyes_selenium', '/Users/serhii/Projects/WORK/APPLITOOLS/eyes.sdk.python/eyes_core', '/Users/serhii/Projects/WORK/APPLITOOLS/eyes.sdk.python/eyes_common', '/Users/serhii/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/192.6603.34/PyCharm.app/Contents/helpers/pycharm_display', '/Users/serhii/.pyenv/versions/3.7.2/lib/python37.zip', '/Users/serhii/.pyenv/versions/3.7.2/lib/python3.7', '/Users/serhii/.pyenv/versions/3.7.2/lib/python3.7/lib-dynload', '/Users/serhii/.pyenv/versions/eyes3/lib/python3.7/site-packages', '/Users/serhii/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/192.6603.34/PyCharm.app/Contents/helpers/pycharm_matplotlib_backend']
2019-09-17 14:02:54,017 - pycrunch.discovery.simple - DEBUG - MODULE_DIR /Users/serhii/Projects/WORK/APPLITOOLS/eyes.sdk.python
2019-09-17 14:02:54,040 - pycrunch.discovery.simple - WARNING - importing .tox.selenium.lib.python3.7.site-packages.webencodings.tests
Traceback (most recent call last):
  File "/Users/serhii/.pyenv/versions/3.7.2/envs/eyes3/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/serhii/.pyenv/versions/3.7.2/envs/eyes3/lib/python3.7/site-packages/flask_socketio/__init__.py", line 44, in __call__
    start_response)
  File "/Users/serhii/.pyenv/versions/3.7.2/envs/eyes3/lib/python3.7/site-packages/engineio/middleware.py", line 67, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/serhii/.pyenv/versions/3.7.2/envs/eyes3/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/serhii/.pyenv/versions/3.7.2/envs/eyes3/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/serhii/.pyenv/versions/3.7.2/envs/eyes3/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/serhii/.pyenv/versions/3.7.2/envs/eyes3/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/serhii/.pyenv/versions/3.7.2/envs/eyes3/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/serhii/.pyenv/versions/3.7.2/envs/eyes3/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/serhii/.pyenv/versions/3.7.2/envs/eyes3/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/serhii/.pyenv/versions/3.7.2/envs/eyes3/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/serhii/.pyenv/versions/3.7.2/envs/eyes3/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/serhii/.pyenv/versions/3.7.2/envs/eyes3/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/serhii/.pyenv/versions/3.7.2/envs/eyes3/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/serhii/.pyenv/versions/3.7.2/envs/eyes3/lib/python3.7/site-packages/pycrunch/api/endpoints.py", line 34, in discover_tests
    engine.will_start_test_discovery()
  File "/Users/serhii/.pyenv/versions/3.7.2/envs/eyes3/lib/python3.7/site-packages/pycrunch/session/state.py", line 33, in will_start_test_discovery
    test_set = discovery_engine.find_tests_in_folder(self.folder)
  File "/Users/serhii/.pyenv/versions/3.7.2/envs/eyes3/lib/python3.7/site-packages/pycrunch/discovery/simple.py", line 102, in find_tests_in_folder
    module = importlib.import_module(module_name)
  File "/Users/serhii/.pyenv/versions/3.7.2/lib/python3.7/importlib/__init__.py", line 122, in import_module
    raise TypeError(msg.format(name))
TypeError: the 'package' argument is required to perform a relative import for '.tox.selenium.lib.python3.7.site-packages.webencodings.tests'
```

My `.pycrunch-config.yaml` config:
```
discovery:
  exclusions:
  - tests/functional/
engine:
  runtime: pytest
```

**Comment by gleb-sevruk** [comment]
I remember some issues caused by relative imports. Can you try changing relative imports to absolute (instead of `.tox.selenium` use fully-qualified name, like: `mypackage.tox.selenium`? 

In the meantime, I'll need to investigate is it working at all with relative imports

**Comment by gleb-sevruk** [comment]
and maybe try adding `test_integration.py` to exclusions. There is a place with weird dependencies setup

**Comment by gleb-sevruk** [comment]
@Infernion 
I was able to run `pycrunch-engine` on your project after adding `__init__.py` file to `tests` subfolder. Also i changed line from 
`common_fixtures import *  # noqa` 
to use relative import (in conftest.py)
`from .common_fixtures import *  # noqa`

![image](https://user-images.githubusercontent.com/609801/65159558-f54f0400-da3c-11e9-8e84-39029e5476ea.png)

For those who struggle with the same issue, I would recommend adding `__init__.py` file to `tests` subfolder. 

Current test discovery engine is hand-made, and not using pytest workarounds for loading modules/packages. Maybe in the future there will make sense to use pytest discovery instead of custom implementation

**Comment by Infernion** [comment]
Thanks! It's working!
