### ISSUE TITLE
IDE exception

### ISSUE THREAD

**Issue by hurricup** [gleb-sevruk/pycrunch-engine#91]
Unsure if this is a right place to report IDEA issues, but this repo specified as plugin sources. so, here we go:

Build: PS-231.8109.199
OS: Windows amd64 10.0
Java Vendor: JetBrains s.r.o.
Java Version: 17.0.6
Java Runtime Version: 17.0.6+10-b829.5
Perl Plugin Version: 2023.1
Description: <none>
Message: none
```
java.lang.Throwable: workspace option is deprecated (implementationClass=com.gleb.pycrunch.MyProjComponent)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:549)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:408)
	at com.intellij.serviceContainer.ComponentManagerImpl.access$registerComponents(ComponentManagerImpl.kt:69)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:294)
	at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:46)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:269)
	at com.intellij.openapi.project.impl.DefaultProjectImpl.init(DefaultProject.java:315)
	at com.intellij.openapi.project.impl.DefaultProject$1.init(DefaultProject.java:50)
	at com.intellij.openapi.project.impl.DefaultProjectTimed.get(DefaultProjectTimed.java:33)
	at com.intellij.openapi.project.impl.DefaultProject.getDelegate(DefaultProject.java:138)
	at com.intellij.openapi.project.impl.DefaultProject.getMessageBus(DefaultProject.java:250)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.getDefaultProject(ProjectManagerImpl.kt:213)
	at com.perl5.lang.htmlmason.idea.configuration.AbstractMasonSettings.<init>(AbstractMasonSettings.java:43)
	at com.perl5.lang.htmlmason.idea.configuration.HTMLMasonSettings.<init>(HTMLMasonSettings.java:66)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:319)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:308)
	at com.intellij.util.xmlb.SkipDefaultValuesSerializationFilters.getDefaultValue(SkipDefaultValuesSerializationFilters.java:53)
	at com.intellij.util.xmlb.SkipDefaultValuesSerializationFilters.getDefaultBean(SkipDefaultValuesSerializationFilters.java:46)
	at com.intellij.util.xmlb.SkipDefaultsSerializationFilter.equal(SkipDefaultsSerializationFilter.java:32)
	at com.intellij.util.xmlb.BeanBinding.serializePropertyInto(BeanBinding.java:107)
	at com.intellij.util.xmlb.BeanBinding.serializeInto(BeanBinding.java:92)
	at com.intellij.serialization.xml.KotlinAwareBeanBinding.serializeInto(KotlinAwareBeanBinding.kt:39)
	at com.intellij.util.xmlb.BeanBinding.serialize(BeanBinding.java:83)
	at com.intellij.configurationStore.JdomSerializerImpl.serialize(xmlSerializer.kt:51)
	at com.intellij.configurationStore.XmlSerializer.serialize(xmlSerializer.kt:23)
	at com.intellij.configurationStore.XmlSerializer.serialize$default(xmlSerializer.kt:22)
	at com.intellij.configurationStore.SaveSessionBaseKt.serializeState(SaveSessionBase.kt:46)
	at com.intellij.configurationStore.SaveSessionBase.setState(SaveSessionBase.kt:20)
	at com.intellij.configurationStore.ComponentStoreImpl.setStateToSaveSessionProducer(ComponentStoreImpl.kt:345)
	at com.intellij.configurationScript.providers.MyProjectStore.setStateToSaveSessionProducer(ConfigurationScriptProjectStoreFactory.kt:72)
	at com.intellij.configurationStore.ComponentStoreImpl.commitComponent(ComponentStoreImpl.kt:338)
	at com.intellij.configurationStore.ComponentStoreImpl.commitComponents$intellij_platform_configurationStore_impl(ComponentStoreImpl.kt:235)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.commitComponents$intellij_platform_configurationStore_impl(ComponentStoreWithExtraComponents.kt:89)
	at com.intellij.configurationStore.ComponentStoreImpl$commitComponentsOnEdt$2.invokeSuspend(ComponentStoreImpl.kt:181)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.application.impl.DispatchedRunnable.run(DispatchedRunnable.kt:35)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:666)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:570)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:570)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by gleb-sevruk** [comment]
This place is correct. The plugin doesn't start at all? 

I will test later what is going on, plugin worked correctly on preview versions on PyCharm 2023.1

**Comment by hurricup** [comment]
I have no idea what is going on, i've got this to exception analyzer for my perl plugin :) so, i'm just a messenger for this one.

**Comment by HackerMadCat** [comment]
We also catch exception:

Product: Aqua
Plugin: Java 231.8495
OS: Mac OS X
Java: JetBrains s.r.o. 17.0.6
Date: 04.05.2023

```
java.lang.Throwable: workspace option is deprecated (implementationClass=com.gleb.pycrunch.MyProjComponent)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:549)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:408)
	at com.intellij.serviceContainer.ComponentManagerImpl.access$registerComponents(ComponentManagerImpl.kt:69)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:294)
	at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:46)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:269)
	at com.intellij.openapi.project.impl.DefaultProjectImpl.init(DefaultProject.java:315)
	at com.intellij.openapi.project.impl.DefaultProject$1.init(DefaultProject.java:50)
	at com.intellij.openapi.project.impl.DefaultProjectTimed.get(DefaultProjectTimed.java:33)
	at com.intellij.openapi.project.impl.DefaultProject.getDelegate(DefaultProject.java:138)
	at com.intellij.openapi.project.impl.DefaultProject.getMessageBus(DefaultProject.java:250)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.getDefaultProject(ProjectManagerImpl.kt:213)
	at com.intellij.ide.util.projectWizard.ProjectWizardUtil.preselectJdkForNewModule(ProjectWizardUtil.java:122)
	at com.intellij.ide.util.projectWizard.ProjectWizardUtil.preselectJdkForNewModule(ProjectWizardUtil.java:93)
	at com.intellij.openapi.roots.ui.configuration.JdkComboBoxKt.createSdkComboBox(JdkComboBox.kt:107)
	at com.intellij.openapi.roots.ui.configuration.JdkComboBoxKt.sdkComboBox(JdkComboBox.kt:70)
	at com.intellij.openapi.roots.ui.configuration.JdkComboBoxKt.sdkComboBox$default(JdkComboBox.kt:54)
	at com.intellij.ide.projectWizard.generators.IntelliJNewProjectWizardStep$setupJavaSdkUI$1.invoke(IntelliJNewProjectWizardStep.kt:87)
	at com.intellij.ide.projectWizard.generators.IntelliJNewProjectWizardStep$setupJavaSdkUI$1.invoke(IntelliJNewProjectWizardStep.kt:85)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:61)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:48)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:23)
	at com.intellij.ide.projectWizard.generators.IntelliJNewProjectWizardStep.setupJavaSdkUI(IntelliJNewProjectWizardStep.kt:85)
	at com.intellij.ide.projectWizard.generators.IntelliJJavaNewProjectWizard$Step.setupSettingsUI(IntelliJJavaNewProjectWizard.kt:33)
	at com.intellij.ide.projectWizard.generators.IntelliJNewProjectWizardStep.setupUI(IntelliJNewProjectWizardStep.kt:177)
	at com.intellij.ide.wizard.NewProjectWizardChainStep.setupUI(NewProjectWizardChainStep.kt:38)
	at com.intellij.ide.wizard.AbstractNewProjectWizardMultiStepBase$getOrCreateStepPanel$panel$1.invoke(AbstractNewProjectWizardMultiStepBase.kt:65)
	at com.intellij.ide.wizard.AbstractNewProjectWizardMultiStepBase$getOrCreateStepPanel$panel$1.invoke(AbstractNewProjectWizardMultiStepBase.kt:64)
	at com.intellij.ui.dsl.builder.BuilderKt.panel(builder.kt:19)
	at com.intellij.ide.wizard.AbstractNewProjectWizardMultiStepBase.getOrCreateStepPanel(AbstractNewProjectWizardMultiStepBase.kt:64)
	at com.intellij.ide.wizard.AbstractNewProjectWizardMultiStepBase.access$getOrCreateStepPanel(AbstractNewProjectWizardMultiStepBase.kt:13)
	at com.intellij.ide.wizard.AbstractNewProjectWizardMultiStepBase$setupUI$1$1.invoke(AbstractNewProjectWizardMultiStepBase.kt:53)
	at com.intellij.ide.wizard.AbstractNewProjectWizardMultiStepBase$setupUI$1$1.invoke(AbstractNewProjectWizardMultiStepBase.kt:49)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:61)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:23)
	at com.intellij.ui.dsl.builder.Panel.row$default(Panel.kt:70)
	at com.intellij.ide.wizard.AbstractNewProjectWizardMultiStepBase.setupUI(AbstractNewProjectWizardMultiStepBase.kt:49)
	at com.intellij.ide.wizard.AbstractNewProjectWizardMultiStepBase$getOrCreateStepPanel$panel$1.invoke(AbstractNewProjectWizardMultiStepBase.kt:65)
	at com.intellij.ide.wizard.AbstractNewProjectWizardMultiStepBase$getOrCreateStepPanel$panel$1.invoke(AbstractNewProjectWizardMultiStepBase.kt:64)
	at com.intellij.ui.dsl.builder.BuilderKt.panel(builder.kt:19)
	at com.intellij.ide.wizard.AbstractNewProjectWizardMultiStepBase.getOrCreateStepPanel(AbstractNewProjectWizardMultiStepBase.kt:64)
	at com.intellij.ide.wizard.AbstractNewProjectWizardMultiStepBase.access$getOrCreateStepPanel(AbstractNewProjectWizardMultiStepBase.kt:13)
	at com.intellij.ide.wizard.AbstractNewProjectWizardMultiStepBase$setupUI$1$1.invoke(AbstractNewProjectWizardMultiStepBase.kt:53)
	at com.intellij.ide.wizard.AbstractNewProjectWizardMultiStepBase$setupUI$1$1.invoke(AbstractNewProjectWizardMultiStepBase.kt:49)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:61)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:23)
	at com.intellij.ui.dsl.builder.Panel.row$default(Panel.kt:70)
	at com.intellij.ide.wizard.AbstractNewProjectWizardMultiStepBase.setupUI(AbstractNewProjectWizardMultiStepBase.kt:49)
	at com.intellij.ide.wizard.NewProjectWizardChainStep.setupUI(NewProjectWizardChainStep.kt:38)
	at com.intellij.ide.wizard.NewProjectWizardStepPanel$component$2$1.invoke(NewProjectWizardStepPanel.kt:21)
	at com.intellij.ide.wizard.NewProjectWizardStepPanel$component$2$1.invoke(NewProjectWizardStepPanel.kt:20)
	at com.intellij.ui.dsl.builder.BuilderKt.panel(builder.kt:19)
	at com.intellij.ide.wizard.NewProjectWizardStepPanel$component$2.invoke(NewProjectWizardStepPanel.kt:20)
	at com.intellij.ide.wizard.NewProjectWizardStepPanel$component$2.invoke(NewProjectWizardStepPanel.kt:19)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.intellij.ide.wizard.NewProjectWizardStepPanel.getComponent(NewProjectWizardStepPanel.kt:19)
	at com.intellij.ide.wizard.AbstractNewProjectWizardBuilder$BridgeStep.getComponent(AbstractNewProjectWizardBuilder.kt:62)
	at com.intellij.ide.wizard.AbstractNewProjectWizardBuilder$BridgeStep.getComponent(AbstractNewProjectWizardBuilder.kt:52)
	at com.intellij.ide.projectWizard.ProjectTypeStep.showCustomOptions(ProjectTypeStep.java:553)
	at com.intellij.ide.projectWizard.ProjectTypeStep.projectTypeChanged(ProjectTypeStep.java:465)
	at com.intellij.ide.projectWizard.ProjectTypeStep.lambda$new$3(ProjectTypeStep.java:207)
	at java.desktop/javax.swing.JList.fireSelectionValueChanged(JList.java:1831)
	at java.desktop/javax.swing.JList$ListSelectionHandler.valueChanged(JList.java:1845)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:224)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:204)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:251)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:448)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:458)
	at java.desktop/javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:502)
	at java.desktop/javax.swing.JList.setSelectedIndex(JList.java:2232)
	at com.intellij.ide.projectWizard.ProjectTypeStep.<init>(ProjectTypeStep.java:236)
	at com.intellij.ide.projectWizard.NewProjectWizard.init(NewProjectWizard.java:60)
	at com.intellij.ide.projectWizard.NewProjectWizard.<init>(NewProjectWizard.java:49)
	at com.intellij.ide.actions.NewProjectAction.actionPerformed(NewProjectAction.java:24)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:333)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:307)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:356)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:307)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeScreenActionsUtil.performAnActionForComponent(WelcomeScreenActionsUtil.java:102)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeScreenActionsUtil$LargeIconWithTextWrapper.lambda$new$0(WelcomeScreenActionsUtil.java:139)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6656)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
	at java.desktop/java.awt.Component.processEvent(Component.java:6421)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2804)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:790)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:763)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:761)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:666)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:614)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:569)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by gleb-sevruk** [comment]
Any more details regarding Pycharm version/plugin version and steps to reproduce?

**Comment by HackerMadCat** [comment]
It is exception from [Aqua](https://www.jetbrains.com/aqua/). There are no steps to reproduce. It is exception from read circle in right down corner of IDE. You may see that.

I can guess how you can reproduce it. You need to install your plugin into any IDE. For example in IntelliJ Idea you need to reboot IDE and create new Intellij java project using new project wizard (Press new project on welcome screen). This exception should be in logs or in dialog under read circle in right down corner.

**Comment by gleb-sevruk** [comment]
Okay, I see the problem now;

Marketplace suggests some really old version of plugin:
<img width="321" alt="image" src="https://github.com/gleb-sevruk/pycrunch-engine/assets/609801/bbc219e0-740d-4649-8016-70dd124d979d">

**Comment by HackerMadCat** [comment]
I cannot give you proper suggestions here. If you cannot solve this issue then you can discuss it with JetBrains Marketplace support or in youtrack.

**Comment by gleb-sevruk** [comment]
I will figure out why there is only old version available with Jetbrains support and post update here

**Comment by gleb-sevruk** [comment]
The version 0.8 of Pycrunch supports Aqua from its 171+ version onwards.
However, in subsequent updates of Pycrunch, starting from version 0.8.1, the support for Aqua, among some other products, has been discontinued.

<img width="287" alt="image" src="https://github.com/gleb-sevruk/pycrunch-engine/assets/609801/8757e73a-3745-4acb-a06d-e42e40909298">

Are you using this plugin for Python-related code inside of Aqua?

I have changes supported versions so it will not be possible to download it anymore (anyway the 0.8 is _really_ outdated)

**Comment by HackerMadCat** [comment]
> Are you using this plugin for Python-related code inside of Aqua?

Our users try to use your plugin inside Aqua. I don't know why they use it.

**Comment by gleb-sevruk** [comment]
In that case, I would recommend installing latest version of plugin from disk

https://github.com/gleb-sevruk/pycrunch-engine/files/11599216/pycrunch-intellij-connector-1.5.1.zip

**Comment by gleb-sevruk** [comment]
Closing and changing minimum plugin version requirements
